name: CI/CD Pipeline (Simplified)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Verify dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Build Docker image
        run: docker build -t ai_trading_assistant:latest .

      - name: Test Docker container
        run: docker run --rm ai_trading_assistant:latest echo "Container built successfully"
