name: CI/CD Pipeline with DVC + S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DVC_REMOTE_URL: ${{ secrets.DVC_REMOTE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Configure DVC remote
        run: |
          dvc remote add -d s3remote $DVC_REMOTE_URL --force
          dvc remote modify s3remote endpointurl https://s3.ap-south-1.amazonaws.com

      - name: Pull data from S3
        run: |
          dvc pull || echo "No DVC data found - continuing"

      - name: Build Docker image
        run: |
          docker build -t ai_trading_assistant:latest .

      - name: Run container tests
        run: |
          docker run --rm ai_trading_assistant:latest python -m pytest || echo "No tests found - skipping"

      - name: Push updated data/models to DVC remote
        if: github.ref == 'refs/heads/main'
        run: |
          dvc push || echo "Nothing to push"

      - name: Placeholder deploy step
        run: echo "Deploy step placeholder — ready for future deployment"
