name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all]

      - name: Pull data from DVC remote
        run: dvc pull || echo "No DVC remote found, skipping."

      - name: Run tests
        run: |
          pytest || echo "No tests found."

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ai_trading_assistant:latest .

      - name: Push to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ai_trading_assistant:latest ghcr.io/${{ github.repository_owner }}/ai_trading_assistant:latest
          docker push ghcr.io/${{ github.repository_owner }}/ai_trading_assistant:latest
